---
title: "Применение средств и методов OSINT"
author: Шабанов Р.В.
format: 
    md:
        output-file: readme.md
engine: knitr
---

## Цель работы

1. Освоить базовые подходы процессов OSINT

2. Освоить современные инструменты поиска и сбора информации

3. Освоить инструменты совместной работы в ходе аналитической деятельности

## Задание

1. Собрать информацию о компании Profiscope

2. Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации

3. Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.

4. Сформировать представление о рынке отечественных решений ИБ

## Ход работы

### 1. Основная информация о компании

Полное название компании - ООО "ПРОФИСКОП"

ИНН - 7813227385

ОГРН - 1157847261824

Юридический адрес - 196105, г. Санкт-Петербург, ул. Свеаборгская, 4, помещ. 9

[Источник](https://b2book.ru/inn/7813227385-ooo-profiskop/) 

### 2. Структура компании

Генеральный директор - Смирнов Алексей Алексеевич

Учредители:

Рожденственский Игорь Всеволодович с 30.07.2015 - 14.10.2022
Смирнов Алексей Алексеевич с 30.07.2015 - по настоящее времся
Тяпочкин Константин Сергеевич - 30.07.2015 - 04.04.2023

[Источник](https://b2book.ru/inn/7813227385-ooo-profiskop/)

### 3. Основные направления деятельности компании

#### Услуги:

Технический аудит - услуга выявления недостатков в программном обеспечении. Помощь в приемке результатов от подрядчика

Помощь при M&A - услуга помощи руководителям и владельцам бизнеса понять состав ПО. Помощь в выявлении юридических рисков, таких как заимствование, копирование кода, нарушение условий лицензирования

Разработка продукта - услуга создания собственных автоматизированных решений для композиционного анализа исходного кода.

[Источник](https://profiscope.io)

#### Производимые продукты:

Code Scoring - оригинальное решение для анализа и оценки кодовой базы на лицензионное соответствие, наличие известных уязвимостей и уровня технического долга.

Главным достоинством по сравнению с другими SCA-решениями является установка авторства, что позволяет определить не только идентичный код, но и схожий

[Источник](https://www.itsec.ru/articles/codescoring-rossijskoe-reshenie-dlya-kompozicionnogo-analiza-koda)

#### Используемые технологии, языки программирования:

Java

JavaScript

Python

C

C++

GO

C#

Php

Ruby

TypeScript

Swift

Kotlin

[Источник](https://codescoring.ru)

### 4. Основные клиенты компании:

##### Информация о клиентах компании, которых удалось найти:

Дмитрий Матюшкин - Технический директор в ГК "Монополия"

Ярослав Марков - Директор по инвестициям в ГК "Ташир МЕДИКА"

[Источник](https://profiscope.io/audit#rec517523049)

### 5. Основные веб-сайты компании и ее продуктов

[Основной веб-сайт](https://profiscope.io)

[Веб-сайт продукта](https://codescoring.ru)

### 6. Публичные сотрудники компании

Единственные сотрудники, которые светились на конференциях - это Смирнов Алексей Алексеевич (Генеральный директор) и Константин Тяпочкин Сергеевич (Учредитель)

[Алексей Смирнов](https://www.youtube.com/watch?v=wcjmNu8cbek)
[Константин Тяпочкин](https://www.youtube.com/watch?v=R8A0fAfA8Kk)

[Телеграмм канал](https://web.telegram.org/a/#-1568386479)
[Телеграмм канал 2](https://web.telegram.org/a/#-1306717588)
[Ютуб канал](https://www.youtube.com/@codescoring)

#### Партнеры компании

Jet

Cross Technologies

Angara Security

РЕГНАНС

Axoft

Информзащита

Lins

Softline

Netrika.

Hilbert Team

Express

ЛАНИТ

КСБ-СОФТ

[Источник](https://profiscope.io)

### 7. Основные достижения, ключевые продукты компании

Ключевым, и пожалуй, единственным продуктом является Code Scoring, который предоставляет решения для компонентного анализа, управления лицензиями и анализу кода

## Вывод

В результате проделанной работы была получена информация о компании Profiscope с помощью метода OSINT  